# Default config is merged with the overrides in this file.  
# https://zitadel.com/docs/self-hosting/manage/configure#database-initialization-file
#
# These steps only run if Zitadel is started with the `start-from-init` command.  The 
# initialization is idempotent when run multiple times with the same Zitadel version.

FirstInstance:
  LoginClientPatPath: '/idp/login-client.pat'
  Org:
    Name: 'cds-snc'
    Human:
      PasswordChangeRequired: false
    LoginClient:
      Machine:
        Name: 'Default IAM_LOGIN_CLIENT'
      Pat:
        ExpirationDate: '2029-01-01T00:00:00Z'
