name: Workflow Pull Request
on:
  pull_request:
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/scripts/check-workflow-run-trigger.sh"

permissions:
  contents: read

jobs:
  workflow-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Check workflow run trigger
        run: |
          .github/workflows/scripts/check-workflow-run-trigger.sh
