name: Workflow failure

on:
  workflow_run:
    workflows:
      - "Docker build and push Staging"
      - "Docker deploy Staging"
      - "Terraform Apply Staging"
      - "Terraform Drift Check Staging"
    types:
      - completed

permissions:
  contents: none

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    env:
      WORKFLOW_NAME: '${{ github.event.workflow_run.name }}'
      WORKFLOW_URL: '${{ github.event.workflow_run.html_url }}'
    steps:
      - name: Determine target ops channel
        id: webhook
        run: |
          WORKFLOW_NAME_LOWER="$(echo ${WORKFLOW_NAME} | tr '[:upper:]' '[:lower:]')"
          if [[ "$WORKFLOW_NAME_LOWER" == *"staging"* ]]; then
            echo "SLACK_WEBHOOK_URL=${{ secrets.STAGING_CLOUDWATCH_ALERT_SLACK_WEBHOOK }}" >> $GITHUB_OUTPUT
          else
            echo "SLACK_WEBHOOK_URL=${{ secrets.PROD_CLOUDWATCH_ALERT_SLACK_WEBHOOK }}" >> $GITHUB_OUTPUT
          fi

      - name: Notify Slack
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: Unified Accounts workflow failed: <${{ github.event.workflow_run.html_url }}|${{ github.event.workflow_run.name }}>"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ steps.webhook.outputs.SLACK_WEBHOOK_URL }}
